# Generated by Django 4.2.6 on 2023-10-20 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='datetime_finished',
            field=models.DateField(default=datetime.datetime(2023, 11, 19, 18, 54, 58, 591949), verbose_name='Дата завершения'),
        ),
    ]
